FROM node:20.9-bullseye-slim

WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

EXPOSE 5173

CMD ["npx", "next", "dev", "-p", "5173"]
