import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
      <html lang="en">
      <body className="min-h-screen flex flex-col">
      <header className="bg-white shadow">
        {/* Import and use your Header component here */}
      </header>
      <main className="flex-grow">{children}</main>
      <footer className="bg-gray-100 text-center py-4">
        {/* Footer content */}
      </footer>
      </body>
      </html>
  );
}
